name: vai-lab-env
channels:
  - conda-forge
dependencies:
  - python=3.6
  - c-compiler
  - pandas
  - pillow
  - scikit-learn
  - ttkwidgets
  - opencv
  - pybullet
  - attrs
  - pip
  - pip:
    - .
