
[build-system]
<<<<<<< HEAD
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "aidesign"
=======
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vailabs"
>>>>>>> c649e33a9f1f792ff992e6340997bb4d131b4d24
authors = [
    {name = "Chris McGreavy", email = "chris.mcgreavy@aalto.fi"},
    {name = "Carlos Sevilla Salcedo", email = "carlos.sevillasalcedo@aalto.fi"}
]
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: MIT License",
]
requires-python = ">=3.8"
version = "1.0"
description = "AI assisted Virtual Laboratory framework."

dependencies = [
    "numpy",
    "tk", # package name of tkinter
    "pillow", # package name of PIL
    "pandas",
    "sklearn",
    "ttkwidgets"
]

[project.urls]
Source = "https://github.com/AaltoPML/VAI-labs"
