
[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "aidesign"
authors = [
    {name = "Chris McGreavy", email = "chris.mcgreavy@aalto.fi"},
    {name = "Carlos Sevilla Salcedo", email = "carlos.sevillasalcedo@aalto.fi"}
]
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: MIT License",
]
requires-python = ">=3.8"
version = "1.0"
description = "AI assisted Virtual Laboratory framework."

dependencies = [
    "numpy",
    "tk", # package name of tkinter
    "pillow", # package name of PIL
    "pandas",
    "sklearn",
    "ttkwidgets",
    "pytest"
]

[project.urls]
Source = "https://github.com/AaltoPML/VAI-labs"


[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"

[project.scripts]
flit = "flit:main"
