name: pytest

on:
  pull_request:
  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
        tags:
          description: 'Test scenario tags' 

defaults:
  run:
    shell: bash -l {0}

jobs:
  ubuntu:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      # setup gcc
      #- name: apt install
      #  run: sudo apt-get install python3-tk

      # pip cache
      #- name: pip cache
      #  uses: actions/setup-python@v4
      #  with:
      #    python-version: {{ matrix.python-version }}
      #    cache: 'pip'
      
      # pip install
      #- name: pip install
      #  run: python3 -m venv venv && venv/bin/python -m pip install -U pip attrs && venv/bin/python -m pip install .

      # pytest
      #- name: Run pytest
      #  uses: coactions/setup-xvfb@v1
      #  with:
      #    run: venv/bin/pytest --cov=./src/vai_lab -v --cov-report=xml:./coverage.xml --cov-report term-missing