name: pytest

on:
  pull_request:
  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
        tags:
          description: 'Test scenario tags' 

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        #python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      # setup gcc
      - name: apt install
        run: sudo apt-get install gcc python3-tk build-essential
        #run: sudo apt-get install gcc python3-tk
        #uses: egor-tensin/setup-gcc@v1
        #with:
        #  version: latest
        #  platform: x64

      # pip cache
      - name: pip install
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      # pip install
      - name: pip install
        run: python -m pip install -U pip && python -m pip install .

      # pytest
      - name: Run pytest
        uses: coactions/setup-xvfb@v1
        with:
          run: pytest --cov=./src/vai_lab -v --cov-report=xml:./coverage.xml --cov-report term-missing
