name: CI Tests

on:
  pull_request:
  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
        tags:
          description: 'Test scenario tags' 

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        #python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      # micromamba
      #- name: Create Conda environment
      #  uses: mamba-org/provision-with-micromamba@main
      #  with:
      #    environment-file: environment.yml
      #    cache-env: true

      # pytest: fails because gui
      #- name: Run pytest
      #  run: pytest --cov=./src/vai_lab -v --cov-report=xml:./coverage.xml --cov-report term-missing

      # setup gcc
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      # pip install
      - name: pip install
        run: python -m pip install -U pip && python - pip install .
        
      # pytest: fails  because pytest tries to run outside conda env
      - name: Run pytest
        uses: coactions/setup-xvfb@v1
        with:
          run: pytest --cov=./src/vai_lab -v --cov-report=xml:./coverage.xml --cov-report term-missing
