name: Test VAI-Lab

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
      - name: Test with pytest
        run: |
          pip install pytest
          pip install pytest-cov
          export DISPLAY=:0
          pytest --cov=.src/vai_lab -v --cov-report=xml:./coverage.xml --cov-report term-missing
# #      - name: Typecheck with mypy
# #        run: |
# #          source $VENV
# #          make typecheck