name: CI Tests

on:
  pull_request:
  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
        tags:
          description: 'Test scenario tags' 

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        #python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      # micromamba
      #- name: Create Conda environment from environment.yml
      #  uses: mamba-org/provision-with-micromamba@main
      #  with:
      #    environment-file: environment.yml
      #  #with:
      #  #  cache-env: true
      #  shell: bash -l {0}
      #  #run: python -c "import pytest"

      # pytest
      #- name: Run pytest
      #  uses: coactions/setup-xvfb@v1
      #  with:
      #    run: pytest --cov=./src/vai_lab -v --cov-report=xml:./coverage.xml --cov-report term-missing
