name: CI Tests

on:
  pull_request:
  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
        tags:
          description: 'Test scenario tags' 

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        #python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      # micromamba
      #- name: Create Conda environment from environment.yml

      # pytest
      - name: Run pytest
        uses: mamba-org/provision-with-micromamba@main        
        with:
          cache-env: true
        uses: coactions/setup-xvfb@v1
        with:
          run: pytest --cov=./src/vai_lab -v --cov-report=xml:./coverage.xml --cov-report term-missing

        # Note: hankolsen/xvfb-action@dcb076c1c3802845f73bb6fe14a009d8d3377255 is a 
        # PR waiting to be merged to GabrielBB/xvfb-action@v1.6 to update xvfb-action
        # to node.js 16. After the merge, switch back to GabrielBB/xvfb-action@v1.6