name: CI Tests

on:
  pull_request:
  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
        tags:
          description: 'Test scenario tags' 

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.10
          mamba-version: "*"
          channel-priority: true
          activate-environment: vailab
          environment-file: environment.yml
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
      - name: Test with pytest
        # uses: GabrielBB/xvfb-action@v1.6
        uses: hankolsen/xvfb-action@dcb076c1c3802845f73bb6fe14a009d8d3377255
        with:
          run: |
            pip install pytest pytest-cov
            pytest --cov=./src/vai_lab -v --cov-report=xml:./coverage.xml --cov-report term-missing


        # Note: hankolsen/xvfb-action@dcb076c1c3802845f73bb6fe14a009d8d3377255 is a 
        # PR waiting to be merged to GabrielBB/xvfb-action@v1.6 to update xvfb-action
        # to node.js 16. After the merge, switch back to GabrielBB/xvfb-action@v1.6