name: sphinx

on: [push, pull_request, workflow_dispatch]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # pip cache
      - name: pip cache
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      # pip install
      - name: pip install
        run: python3 -m pip install -U pip && python3 -m pip install -r sphinx_requirements.txt
      - name: build
        run: |
          sphinx-apidoc --templatedir docs/source/_templates/apidoc/ -o docs/source src/vai_lab
          sphinx-build -M html docs/source docs/build

      # publish
      - name: publish gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true